// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCqWC-NxZZ73Frhjm0d4HFQgB8Ns_EOBTc',
    appId: '1:174048970421:web:bc9faf4706609ba2fda0fc',
    messagingSenderId: '174048970421',
    projectId: 'cash-collector-app',
    authDomain: 'cash-collector-app.firebaseapp.com',
    storageBucket: 'cash-collector-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDMwEQ8opYqSuA19xdjYj5AKelG2xyJ5JU',
    appId: '1:174048970421:android:6b1512839a16ec6efda0fc',
    messagingSenderId: '174048970421',
    projectId: 'cash-collector-app',
    storageBucket: 'cash-collector-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDf2m7HN-HRnvwk6Z5ZrIQ19EaY8ScphaY',
    appId: '1:174048970421:ios:a6405bff3bfb6a9dfda0fc',
    messagingSenderId: '174048970421',
    projectId: 'cash-collector-app',
    storageBucket: 'cash-collector-app.firebasestorage.app',
    iosBundleId: 'com.example.cashCollector',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDf2m7HN-HRnvwk6Z5ZrIQ19EaY8ScphaY',
    appId: '1:174048970421:ios:a6405bff3bfb6a9dfda0fc',
    messagingSenderId: '174048970421',
    projectId: 'cash-collector-app',
    storageBucket: 'cash-collector-app.firebasestorage.app',
    iosBundleId: 'com.example.cashCollector',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCqWC-NxZZ73Frhjm0d4HFQgB8Ns_EOBTc',
    appId: '1:174048970421:web:8d521460316ba245fda0fc',
    messagingSenderId: '174048970421',
    projectId: 'cash-collector-app',
    authDomain: 'cash-collector-app.firebaseapp.com',
    storageBucket: 'cash-collector-app.firebasestorage.app',
  );
}
